version: '3.8'

services:
  api:
    build: .
    container_name: postalwiki-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - postalwiki-network

networks:
  postalwiki-network:
    driver: bridge 