const adultKeywords_exact_match = [
    "accidental creampie",
    "accidental orgasm",
    "adult affiliate",
    "adult affiliates",
    "adult babies",
    "adult baby",
    "adult cams",
    "adult chat",
    "adult clips",
    "adult confessions",
    "adult content",
    "adult dating",
    "adult domme",
    "adult dvd",
    "adult erotica",
    "adult film",
    "adult friendfinder",
    "adult massage",
    "adult movies",
    "adult products",
    "adult schoolgirl",
    "adult strip",
    "adult video",
    "adult webcam",
    "adult xxx",
    "adultbabies",
    "adultbaby",
    "adultconfessions",
    "adultfriendfinder",
    "adulttube",
    "adultwebcams",
    "afspraakjes",
    "afspreken",
    "age play",
    "agencje towarzyskie",
    "alexa scout",
    "alexascout",
    "amateur cuckolds",
    "amateur models",
    "amateur sex",
    "anal",
    "animalsex",
    "animal sex",
    "annunci erotici",
    "annunci trans",
    "anonse erotyczne",
    "anonse towarzyskie",
    "asian babe",
    "asian beauties",
    "asian cams",
    "asian chat",
    "asian daddies",
    "asian gay",
    "asian girls",
    "asian sex",
    "asian tube",
    "asian webcams",
    "asiantube",
    "ass bitches",
    "ass sex",
    "ass tube",
    "backdoor action",
    "bangvan",
    "bareback",
    "bbw chat",
    "bbw tube",
    "bbw videos",
    "bbw webcam",
    "bbwtube",
    "bdsm",
    "beianrufsex",
    "big breast",
    "big dick",
    "big girls",
    "bigbreast",
    "bisex",
    "blowjobs",
    "bodyrotic",
    "bondage",
    "bongacams",
    "bongacash",
    "boob cam",
    "brazzers",
    "bukkake",
    "butt holes",
    "butt plugs",
    "butt sex",
    "call girls",
    "cam girl",
    "cam girls",
    "cam models",
    "cam2cam",
    "cams sex",
    "camsex",
    "casual sex",
    "chaturbate",
    "cheating hotwives",
    "cock",
    "cokegirlx",
    "college sex",
    "cuckold",
    "cuckolds",
    "cum",
    "czech casting",
    "deepthroat",
    "desi girls",
    "desi sex",
    "diaper lovers",
    "dick",
    "dicks",
    "dietikon",
    "dildopenetrations",
    "dildos",
    "discreet outcall",
    "domaine parque",
    "dominatrix",
    "ebony cams",
    "ebony chat",
    "ebony sex",
    "ebony videos",
    "ed2k",
    "ejaculation",
    "elephant list",
    "elephant tube",
    "elephantlist",
    "erotic fantasies",
    "erotic live",
    "erotic massage",
    "erotic trends",
    "erotica videos",
    "erotische massages",
    "escort directory",
    "escort girls",
    "escort pleasures",
    "escort services",
    "etube",
    "exotic dancers",
    "fakehub",
    "faketaxi",
    "feet sex",
    "femdom",
    "fetish",
    "fisting",
    "flexigirls",
    "flirt4free",
    "foot worship",
    "footjob",
    "freesexe",
    "fuck",
    "gangbang",
    "gay cam",
    "gay cams",
    "gay chat",
    "gay dvds",
    "gay hardcore",
    "gay magazines",
    "gay movies",
    "gay mpeg",
    "gay sex scenes",
    "gay tube",
    "gay video",
    "gay videos",
    "gayboys",
    "gaycam",
    "gaywomen",
    "get laid",
    "gfe massage",
    "gigantic boobs",
    "girl hookups",
    "girls online",
    "gonzo movies",
    "groupsex",
    "hand relief",
    "handjob",
    "happy ending",
    "hardcore",
    "hd sex",
    "hentai",
    "hot sex",
    "huge boobs",
    "hymen photo",
    "incontri escort",
    "indian sex",
    "indiansex",
    "italian escort",
    "jack off",
    "jackoff",
    "japanese hentai",
    "jerk off",
    "jerkoff",
    "jugg cash",
    "juggcash",
    "kinky angels",
    "kinky dates",
    "live cam",
    "live cams",
    "live sex",
    "livejasmin",
    "livesex",
    "man sex",
    "masturbators",
    "milf",
    "milfs",
    "monsterboobs",
    "naked girls",
    "naked massage",
    "nude amateur",
    "nude boys",
    "nude cam",
    "nude girls",
    "nude men",
    "nude tube",
    "nudity",
    "online sex",
    "onlyfans",
    "oral sex",
    "orgy",
    "partysex",
    "penis",
    "phone chat",
    "phone sex",
    "piss",
    "pissing",
    "porn",
    "private amateurs",
    "private sex",
    "prostitutie",
    "pussy",
    "random strangers",
    "real sex",
    "rimming",
    "sex animations",
    "sex anonse",
    "sex asian",
    "sex cams",
    "sex chat",
    "sex chats",
    "sex clips",
    "sex dating",
    "sex games",
    "sex girls",
    "sex in romania",       
    "sex movies",
    "sex photos",
    "sex shows",
    "sex sites",
    "sex stuff",
    "sex toys",
    "sex tube",
    "sex video",
    "sex videos",
    "sex webcams",
    "sexafspraak",
    "sexcam",
    "sexchat",
    "sexclub",
    "sexcontortion",
    "sexflexvideo",
    "sexgames",
    "sexhymen",
    "sexowap",
    "sexploitation",
    "sexshow",
    "sexting",
    "sextube",
    "sexual fantasy",
    "sexy encounters",
    "sinfully sexy",
    "stream explicit",
    "strip chat",
    "strip club",
    "stripchat",
    "strippers",
    "striptease",
    "teen pussy",
    "telefonsex",
    "telesex",
    "tranny",
    "transerotica",
    "tv for adults",
    "webcam model",
    "webcam models",
    "webcamsex",
    "wet panties",
    "wet panty",
    "whores",
    "xxx",
];

const adultKeywords_contains = [
    "adult",
    "age restricted",
    "age verification",
    "boobs",
    "breast",
    "breasts",
    "erotic",
    "erotica",
    "escort",
    "exotic",
    "explicit",
    "free cam",
    "free cams",
    "gay",
    "hot wives",
    "hotwives",
    "lesbian",
    "massage",
    "models",
    "no minors allowed",
    "online models",
    "pleasures",
    "sex",
    "sexy",
    "tit",
    "tits",
    "transexual",
    "uncensored",
    "webcam",
    "webcams",
    "nude",
    "naked",
    "nudes",
    "gays",
    "boobs",
];

module.exports = {
    adultKeywords_exact_match,
    adultKeywords_contains,
};
