name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 1337
        script: |
          # Install Node.js 18 using NVM (Node Version Manager)
          if ! command -v nvm &> /dev/null; then
            echo "Installing NVM..."
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          fi
          
          # Install and use Node.js 18
          nvm install 18
          nvm use 18
          
          # Create directory if it doesn't exist
          mkdir -p /home/lysnar/api.postalwiki.co.uk
          cd /home/lysnar/api.postalwiki.co.uk
          
          # Initialize git if not already initialized
          if [ ! -d .git ]; then
            git init
            git remote add origin ${{ secrets.REPOSITORY_URL }}
          fi
          
          # Pull the latest code
          git fetch origin
          git reset --hard origin/main
          
          # Install dependencies
          npm install
          
          # Set proper permissions
          # First, make sure lysnar owns the directory
          chown -R lysnar:lysnar /home/lysnar/api.postalwiki.co.uk
          # Then set permissions that allow nobody (Apache) to read
          chmod -R 755 /home/lysnar/api.postalwiki.co.uk
          
          # Install PM2 locally
          if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2 locally..."
              npm install pm2 --location=global
          fi
          
          # Add PM2 to PATH
          export PATH="$HOME/.npm-global/bin:$PATH"
          
          # Create ecosystem file for PM2
          cat > ecosystem.config.js << 'EOL'
          module.exports = {
            apps: [{
              name: "postalwiki-api",
              script: "npm",
              args: "start",
              env: {
                NODE_ENV: "production",
                PORT: 3000
              }
            }]
          }
          EOL
          
          # Check if the process exists
          if pm2 list | grep -q "postalwiki-api"; then
              echo "Restarting existing application..."
              pm2 restart postalwiki-api
          else
              echo "Starting application for the first time..."
              pm2 start ecosystem.config.js
              pm2 save
              pm2 startup
          fi
          
          # Reload Apache (using sudo since it's required)
          sudo /usr/local/apache/bin/apachectl graceful 