name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/lysnar/api.postalwiki.co.uk
          git pull origin main
          npm install
          npm run build
          # Set proper permissions
          sudo chown -R nobody:nobody /home/lysnar/api.postalwiki.co.uk
          sudo chmod -R 755 /home/lysnar/api.postalwiki.co.uk
          # Restart the application
          pm2 restart postalwiki-api || pm2 start npm --name "postalwiki-api" -- start
          # Reload Apache to ensure proxy settings are updated
          sudo /usr/local/apache/bin/apachectl graceful 