name: Sync Code to Server

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Sync Code to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 1337
        script: |
          # Create directory if it doesn't exist
          mkdir -p /home/lysnar/api.postalwiki.co.uk
          cd /home/lysnar/api.postalwiki.co.uk
          
          # Initialize git if not already initialized
          if [ ! -d .git ]; then
            git init
            git remote add origin ${{ secrets.REPOSITORY_URL }}
          fi
          
          # Pull the latest code
          git fetch origin
          git reset --hard origin/main 