name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/lysnar/api.postalwiki.co.uk
          git pull origin main
          npm install
          # Set proper permissions
          sudo chown -R nobody:nobody /home/lysnar/api.postalwiki.co.uk
          sudo chmod -R 755 /home/lysnar/api.postalwiki.co.uk
          
          # Check if PM2 is installed globally
          if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2 globally..."
              sudo npm install -g pm2
          fi
          
          # Check if the process exists
          if pm2 list | grep -q "postalwiki-api"; then
              echo "Restarting existing application..."
              pm2 restart postalwiki-api
          else
              echo "Starting application for the first time..."
              # Create ecosystem file for PM2
              cat > ecosystem.config.js << EOL
              module.exports = {
                apps: [{
                  name: "postalwiki-api",
                  script: "npm",
                  args: "start",
                  env: {
                    NODE_ENV: "production",
                    PORT: 3000
                  }
                }]
              }
              EOL
              
              # Start the application
              pm2 start ecosystem.config.js
              # Save the PM2 process list
              pm2 save
              # Setup PM2 to start on system boot
              pm2 startup
          fi
          
          # Reload Apache to ensure proxy settings are updated
          sudo /usr/local/apache/bin/apachectl graceful 